apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata
  namespace: solarsystem
  labels:
    name: mongodata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
