apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: solarsystem
  labels:
    name: mongo
spec:
  selector:
    name: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
