apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: solarsystem
  labels:
    name: nginx
spec:
  selector:
    name: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      
